package com.group.View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.group.DAO.DatPhongDAO;
import com.group.DAO.HoaDonDAO;
import com.group.DAO.KhachHangDAO;
import com.group.DAO.PhongDAO;
import com.group.Library.DateHelper;
import com.group.Library.DialogHelper;
import com.group.Library.JDBCHelper;
import com.group.Library.ShareHelper;
import com.group.Model.DatPhong;
import com.group.Model.HoaDon;
import com.group.Model.KhachHang;
import com.group.Model.Phong;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Pham Nhat Hoang
 */
public final class QuanLyPhongJFrame extends javax.swing.JFrame {
    PhongDAO phongDao = new PhongDAO();
    List<Phong> list = new ArrayList<>();
    int index = 0;
    int mode = 0;
    String[] maDP = {"null", "DV001", "DV002", "DV003", "DV004", "DV005"};
    
    DatPhongDAO datPhongDao = new DatPhongDAO();
    KhachHangDAO khachHangDao = new KhachHangDAO();
    HoaDonDAO hoaDonDao = new HoaDonDAO();
    
    /**
     * Creates new form QuanLyPhongJFrame
     */
    public QuanLyPhongJFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jtbDanhSach = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnTim = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhsach = new javax.swing.JTable();
        jtbDatPhong = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtHoVaTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        txtSoPhong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDatPhong = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtNgayDen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNgayDi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtMaDatPhong = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        DV001 = new javax.swing.JCheckBox();
        DV002 = new javax.swing.JCheckBox();
        DV003 = new javax.swing.JCheckBox();
        DV004 = new javax.swing.JCheckBox();
        DV005 = new javax.swing.JCheckBox();
        jtbTraPhong = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSoPhong1 = new javax.swing.JTextField();
        txtLoaiPhong = new javax.swing.JTextField();
        txtNgayThue1 = new javax.swing.JTextField();
        txtNgayTra = new javax.swing.JTextField();
        txtTongGio = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtMaDat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý phòng");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ PHÒNG");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Trạng thái"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng trống", "Phòng có khách" }));

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTim)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tblDanhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phòng", "Loại phòng", "Giá ", "Tình trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhsach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhsachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhsach);

        javax.swing.GroupLayout jtbDanhSachLayout = new javax.swing.GroupLayout(jtbDanhSach);
        jtbDanhSach.setLayout(jtbDanhSachLayout);
        jtbDanhSachLayout.setHorizontalGroup(
            jtbDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtbDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jtbDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
                .addContainerGap())
        );
        jtbDanhSachLayout.setVerticalGroup(
            jtbDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtbDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Danh sách", jtbDanhSach);

        jLabel2.setText("Họ và tên");

        txtSoPhong.setEditable(false);

        jLabel3.setText("SĐT");

        jLabel4.setText("Số CCCD/CMND");

        jLabel5.setText("Ngày đến");

        btnDatPhong.setText("Xác nhận");
        btnDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatPhongActionPerformed(evt);
            }
        });

        btnClear.setText("Clean from");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel7.setText("Số phòng");

        jLabel6.setText("Ngày đi");

        jLabel14.setText("Mã Đặt Phòng");

        txtMaDatPhong.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dịch Vụ"));

        DV001.setText("Dịch vụ phòng ăn +150.000");

        DV002.setText("Dịch vụ giặt là +100.000");

        DV003.setText("Dịch vụ đưa đón +200.000");

        DV004.setText("Dịch vụ spa +250.000");

        DV005.setText("Dịch vụ thuê xe +300.000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DV001)
                    .addComponent(DV002)
                    .addComponent(DV003)
                    .addComponent(DV004)
                    .addComponent(DV005))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DV001)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DV002)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DV003)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DV004)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DV005)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSoPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addComponent(txtHoVaTen)
                        .addComponent(txtSDT)
                        .addComponent(txtCCCD)
                        .addComponent(txtMaDatPhong))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDatPhong))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayDi)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgayDen, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnDatPhong))
                .addContainerGap())
        );

        javax.swing.GroupLayout jtbDatPhongLayout = new javax.swing.GroupLayout(jtbDatPhong);
        jtbDatPhong.setLayout(jtbDatPhongLayout);
        jtbDatPhongLayout.setHorizontalGroup(
            jtbDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtbDatPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jtbDatPhongLayout.setVerticalGroup(
            jtbDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtbDatPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Đặt phòng", jtbDatPhong);

        jLabel8.setText("Số phòng");

        jLabel9.setText("Loại phòng");

        jLabel10.setText("Ngày thuê");

        jLabel11.setText("Ngày trả");

        jLabel12.setText("Tổng ngày");

        txtSoPhong1.setEditable(false);

        txtLoaiPhong.setEditable(false);

        txtNgayThue1.setEditable(false);

        txtNgayTra.setEditable(false);

        txtTongGio.setEditable(false);

        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jLabel15.setText("Mã Đặt");

        txtMaDat.setEditable(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(198, 198, 198))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnThanhToan)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNgayThue1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTongGio, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSoPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(248, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(txtMaDat, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtMaDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSoPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNgayThue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTongGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnThanhToan))
        );

        javax.swing.GroupLayout jtbTraPhongLayout = new javax.swing.GroupLayout(jtbTraPhong);
        jtbTraPhong.setLayout(jtbTraPhongLayout);
        jtbTraPhongLayout.setHorizontalGroup(
            jtbTraPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtbTraPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jtbTraPhongLayout.setVerticalGroup(
            jtbTraPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtbTraPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trả phòng", jtbTraPhong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        int value = jComboBox1.getSelectedIndex();
        
        if (value == 0) {
            String sql = "SELECT * FROM PHONG WHERE TINHTRANG = 0";
            list = phongDao.select(sql);
            load();
            mode = 1;
        } else {
            String sql = "SELECT * FROM PHONG WHERE TINHTRANG = 1";
            list = phongDao.select(sql);
            load();
            mode = 2;
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void tblDanhsachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhsachMouseClicked
        this.index = tblDanhsach.rowAtPoint(evt.getPoint());
        
        if (mode == 1) {
            if (this.index >= 0) {
                String id = (String) tblDanhsach.getValueAt(this.index, 0);
                txtSoPhong.setText(id);
                txtMaDatPhong.setText(getMaDP());
                txtNgayDen.setText(DateHelper.toString(DateHelper.now(), "dd/MM/yyyy"));
                jTabbedPane1.setSelectedIndex(1);
            }
        } else {
            if (this.index >= 0) {
                String id = (String) tblDanhsach.getValueAt(this.index, 0);
                int soPhong = Integer.parseInt(id);
                Phong phong = phongDao.findBySoPhong(soPhong);
                DatPhong datphong = datPhongDao.findBySoPhong(id);
                txtSoPhong1.setText(id);
                txtLoaiPhong.setText(phong.getLoaiPhong());
                txtNgayThue1.setText(DateHelper.toString(datphong.getNgayDen(),"dd/MM/yyyy"));
                txtNgayTra.setText(DateHelper.toString(datphong.getNgayDi(),"dd/MM/yyyy"));
                txtMaDat.setText(datphong.getMaDatPhong());
                
                long ngayThue = 0;
                try {
                    ngayThue = getSoNgayThue(datphong.getNgayDen(), datphong.getNgayDi());
                } catch (ParseException ex) {
                    Logger.getLogger(QuanLyPhongJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                String ngay = String.valueOf(ngayThue);
                txtTongGio.setText(ngay);
                jTabbedPane1.setSelectedIndex(2);
            }
        }
    }//GEN-LAST:event_tblDanhsachMouseClicked

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        String soPhong = txtSoPhong1.getText();
        if (soPhong != null) { 
            ThanhToanJFrame frame = new ThanhToanJFrame(soPhong);
            frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            frame.setVisible(true);
            clearTP();           
            reload();
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed
    
    //Xác nhận đặt phòng
    private void btnDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatPhongActionPerformed
        if(validateAdd()) {
            insert();
            reload();
            jTabbedPane1.setSelectedIndex(0);
        } 
    }//GEN-LAST:event_btnDatPhongActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearDP();
    }//GEN-LAST:event_btnClearActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windown".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QuanLyPhongJFrame().setVisible(true);
        });
    }
    
    public void load() {
        DefaultTableModel model = (DefaultTableModel) tblDanhsach.getModel();
        model.setRowCount(0);
        try {
            for(Phong phong : list) {
                Object[] row = {
                    phong.getSoPhong(),
                    phong.getLoaiPhong(),
                    phong.getGia(),
                    phong.getTinhTrang()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.getMessage();
            DialogHelper.alert(this, "Lỗi truy xuất");
        }
    }
    
    //Tạo mã đặt phòng
    public String getMaDP() {
        Random random = new Random();
        int min = 1000;  
        int max = 9999;

        int randomNumber = random.nextInt(max - min + 1) + min;
        String maDat = "DP" + randomNumber;
        
        DatPhong checkDP = datPhongDao.findByMaDat(maDat);
        if (checkDP != null) {
            randomNumber = random.nextInt(max - min + 1) + min;
            maDat = "DP" + randomNumber;
        }
        return maDat;
    }
    
    //Check điền thông tin
    public boolean validateAdd() {
        String hoTen = txtHoVaTen.getText().trim();
        String soCMND = txtCCCD.getText().trim();
        
        String SDTKhach = txtSDT.getText();
        
        try {
            int SDTKhach1 = Integer.parseInt(txtSDT.getText());
        } catch (NumberFormatException e) {
            DialogHelper.alert(rootPane, "Số điện thoại không đúng định dạng");
            return false;
        }
        
        String ngayDen = txtNgayDen.getText();
        String ngayDi = txtNgayDi.getText();
        
        if (hoTen.equals("")) {
            DialogHelper.alert(rootPane, "Vui lòng nhập họ tên");
            return false;
        } 
        
        if (soCMND.equals("")) {
            DialogHelper.alert(rootPane, "Vui lòng nhập họ tên");
            return false;
        } 
        
        if (SDTKhach.equals("")) {
            DialogHelper.alert(rootPane, "Vui lòng nhập số điện thoại");
            return false;
        }
        
        String dateFormat = "dd/MM/yyyy";

        try {
            SimpleDateFormat sdf = new SimpleDateFormat(dateFormat);
            sdf.parse(ngayDen);
            sdf.parse(ngayDi);
        } catch (ParseException e) {
            DialogHelper.alert(rootPane, "Ngày đến và đi sai định dạng 'dd/MM/yyyy'");
            return false;
        }
        return true;
    }
    
    //Thêm thông tin
    public void insert() {
        //Thu thông tin
        String maDatPhong = txtMaDatPhong.getText();
        String maNV = ShareHelper.USER.getMaNv();
        
        
        String hoTen = txtHoVaTen.getText();
        String soCMND = txtCCCD.getText();
        String soPhong = txtSoPhong.getText();

        int SDTKhach = Integer.parseInt(txtSDT.getText());

        Date ngayDen = DateHelper.toDate(txtNgayDen.getText(), "dd/MM/yyyy");
        Date ngayDi = DateHelper.toDate(txtNgayDi.getText(), "dd/MM/yyyy");

        //Kiểm tra khách tồn tại
        KhachHang checkKH = khachHangDao.findBySDT(SDTKhach);

        //Tạo đối tượng & đưa vào database
        if(checkKH == null) {
            KhachHang khach = new KhachHang(SDTKhach, hoTen, soCMND);
            khachHangDao.insert(khach);
        }
        
        //Tạp đặt phòng
        DatPhong model = new DatPhong(maDatPhong, maNV, SDTKhach, ngayDen, ngayDi, soPhong);
        datPhongDao.insert(model);

        //Tạo hóa đơn
        if(DV001.isSelected()) {
            HoaDon hd = new HoaDon(SDTKhach, maDatPhong, "DV001");
            hoaDonDao.insert(hd);
        }
        if(DV002.isSelected()) {
            HoaDon hd = new HoaDon(SDTKhach, maDatPhong, "DV002");
            hoaDonDao.insert(hd);
        }
        if(DV003.isSelected()) {
            HoaDon hd = new HoaDon(SDTKhach, maDatPhong, "DV003");
            hoaDonDao.insert(hd);
        }
        if(DV004.isSelected()) {
            HoaDon hd = new HoaDon(SDTKhach, maDatPhong, "DV004");
            hoaDonDao.insert(hd);
        }
        if(DV005.isSelected()) {
            HoaDon hd = new HoaDon(SDTKhach, maDatPhong, "DV005");
            hoaDonDao.insert(hd);
        }
    
        
        String sql = "Update Phong set tinhtrang = 1 where sophong = " + soPhong;
        JDBCHelper.executeUpdate(sql);
        
        DialogHelper.alert(rootPane, "Đặt phòng thành công");  
        clearDP();
    }
    
    //Tính số ngày
    private long getSoNgayThue(Date ngayDen, Date ngayDi) throws ParseException {
        long diffDays = 0;
        try {
        String ngayDen1 = DateHelper.toString(ngayDen, "dd/MM/yyyy");
        String ngayDi1 = DateHelper.toString(ngayDi, "dd/MM/yyyy");
        
        Date date1 = new SimpleDateFormat("dd/MM/yyyy").parse(ngayDen1);
        Date date2 = new SimpleDateFormat("dd/MM/yyyy").parse(ngayDi1);

        long diff = date2.getTime() - date1.getTime();
        diffDays = diff / (24 * 60 * 60 * 1000);
        } catch (ExceptionInInitializerError e) {
            e.getMessage();
        }
        return diffDays;
    }
    
    //Clear thông tin đặt phòng
    public void clearDP() {
        txtMaDatPhong.setText("");
        txtHoVaTen.setText("");
        txtCCCD.setText("");
        txtSDT.setText("");
        txtSoPhong.setText("");
        txtNgayDen.setText("");
        txtNgayDi.setText("");
        jTabbedPane1.setSelectedIndex(0);
    }
    
    //Clear thông tin trả phòng
    public void clearTP() {
        txtMaDat.setText("");
        txtSoPhong1.setText("");
        txtLoaiPhong.setText("");
        txtNgayThue1.setText("");
        txtNgayTra.setText("");
        txtTongGio.setText("");
    }
    
    //Clear thông tin tìm kiếm phòng
    public void reload() {
        list = null;
        DefaultTableModel model = (DefaultTableModel) tblDanhsach.getModel();
        model.setRowCount(0);
        try {
            for(Phong phong : list) {
                Object[] row = {
                    phong.getSoPhong(),
                    phong.getLoaiPhong(),
                    phong.getGia(),
                    phong.getTinhTrang()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox DV001;
    private javax.swing.JCheckBox DV002;
    private javax.swing.JCheckBox DV003;
    private javax.swing.JCheckBox DV004;
    private javax.swing.JCheckBox DV005;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDatPhong;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JToggleButton btnTim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jtbDanhSach;
    private javax.swing.JPanel jtbDatPhong;
    private javax.swing.JPanel jtbTraPhong;
    private javax.swing.JTable tblDanhsach;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JTextField txtLoaiPhong;
    private javax.swing.JTextField txtMaDat;
    private javax.swing.JTextField txtMaDatPhong;
    private javax.swing.JTextField txtNgayDen;
    private javax.swing.JTextField txtNgayDi;
    private javax.swing.JTextField txtNgayThue1;
    private javax.swing.JTextField txtNgayTra;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSoPhong;
    private javax.swing.JTextField txtSoPhong1;
    private javax.swing.JTextField txtTongGio;
    // End of variables declaration//GEN-END:variables

      void init(){
        setLocationRelativeTo(null);
    }
}
