package com.group.View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.group.DAO.DatPhongDAO;
import com.group.DAO.DichVuDAO;
import com.group.DAO.HoaDonDAO;
import com.group.DAO.KhachHangDAO;
import com.group.DAO.PhongDAO;
import com.group.Library.DateHelper;
import com.group.Library.DialogHelper;
import com.group.Library.JDBCHelper;
import com.group.Model.DatPhong;
import com.group.Model.DichVu;
import com.group.Model.HoaDon;
import com.group.Model.KhachHang;
import com.group.Model.Phong;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Pham Nhat Hoang
 */
public final class ThanhToanJFrame extends javax.swing.JFrame {
    String soPhong1 = null;
    DatPhongDAO datPhongDao = new DatPhongDAO();
    PhongDAO phongDao = new PhongDAO();
    KhachHangDAO khachHangDao = new KhachHangDAO();
    HoaDonDAO hoaDonDao = new HoaDonDAO();
    DichVuDAO dichVuDao = new DichVuDAO();
    
    
    /**
     * Creates new form ThanhToanJFrame
     * @param soPhong
     */
    public ThanhToanJFrame(String soPhong) {
        initComponents();
        init();
        soPhong1 = soPhong;
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNgayTra = new javax.swing.JTextField();
        txtTongTG = new javax.swing.JTextField();
        txtTongThanhToan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtLoaiPhong = new javax.swing.JTextField();
        txtSoPhong = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnInHoaDon = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        DV001 = new javax.swing.JCheckBox();
        DV002 = new javax.swing.JCheckBox();
        DV003 = new javax.swing.JCheckBox();
        DV004 = new javax.swing.JCheckBox();
        DV005 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THANH TOÁN");

        jLabel3.setText("Thời gian trả phòng");

        jLabel4.setText("Số ngày thuê");

        jLabel5.setText("Tổng tiền thanh toán");

        txtNgayTra.setEditable(false);

        txtTongTG.setEditable(false);

        txtTongThanhToan.setEditable(false);

        jLabel6.setText("Tên Khách hàng");

        txtTenKH.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNgayTra)
                    .addComponent(txtTongTG)
                    .addComponent(txtTongThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(txtTenKH))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTongTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTongThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtLoaiPhong.setEditable(false);
        txtLoaiPhong.setToolTipText("");
        txtLoaiPhong.setBorder(javax.swing.BorderFactory.createTitledBorder("Loại phòng"));

        txtSoPhong.setEditable(false);
        txtSoPhong.setToolTipText("");
        txtSoPhong.setBorder(javax.swing.BorderFactory.createTitledBorder("Số phòng"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        btnInHoaDon.setText("In hóa đơn");
        jPanel3.add(btnInHoaDon);

        btnThanhToan.setText("Xác nhận thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });
        jPanel3.add(btnThanhToan);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dịch Vụ"));

        DV001.setText("Dịch vụ phòng ăn +150.000");

        DV002.setText("Dịch vụ giặt là +100.000");

        DV003.setText("Dịch vụ đưa đón +200.000");

        DV004.setText("Dịch vụ spa +250.000");

        DV005.setText("Dịch vụ thuê xe +300.000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DV001)
                    .addComponent(DV002)
                    .addComponent(DV003)
                    .addComponent(DV004)
                    .addComponent(DV005))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DV001)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DV002)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DV003)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DV004)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DV005)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Xác nhận thanh toán?", "Thanh toán", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            String sql = "Update Phong set tinhtrang = 0 where sophong = " + soPhong1;
            JDBCHelper.executeUpdate(sql);
            
            DatPhong datphong = datPhongDao.findBySoPhong(soPhong1);
            List<HoaDon> list = hoaDonDao.findByMaDat1(datphong.getMaDatPhong());
            if (list != null) {
                DatPhong datPhong = datPhongDao.findBySoPhong(soPhong1);
                String sqlHoaDon = "Delete from hoadon where madat like '" + datPhong.getMaDatPhong() +"'";
                JDBCHelper.executeUpdate(sqlHoaDon);
            }
            String deleteSQL = "Delete from datphong where sophong = " + soPhong1;
            JDBCHelper.executeUpdate(deleteSQL);
            
            DialogHelper.alert(rootPane, "Thanh toán và trả phòng thành công");
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    public void load() {
        double tongTien = 0;
        //Get thông tin
        int id = Integer.parseInt(soPhong1);
        DichVu dichVu = null;
        Phong phong = phongDao.findBySoPhong(id);
        DatPhong datPhong = datPhongDao.findBySoPhong(soPhong1);
        KhachHang khachHang = khachHangDao.findBySDT(datPhong.getSDTKhach());
        
        List<HoaDon> list = hoaDonDao.findByMaDat1(datPhong.getMaDatPhong());
        for (HoaDon hoaDon : list) {
            dichVu = dichVuDao.findByMaDV(hoaDon.getMaDV());
            tongTien += dichVu.getGia();
            System.out.println(tongTien);
            if(dichVu.getMaDV().equals("DV001")) {
                DV001.setSelected(true);
            }
            if(dichVu.getMaDV().equals("DV002")) {
                DV002.setSelected(true);
            }
            if(dichVu.getMaDV().equals("DV003")) {
                DV003.setSelected(true);
            }
            if(dichVu.getMaDV().equals("DV004")) {
                DV004.setSelected(true);
            }
            if(dichVu.getMaDV().equals("DV005")) {
                DV005.setSelected(true);
            }
        }
        
        //Set thông tin phòng
        txtSoPhong.setText(soPhong1);        
        txtLoaiPhong.setText(phong.getLoaiPhong());
        
        //Set Thông tin khách hàng
        txtTenKH.setText(khachHang.getHoTen());
        
        //Set Thông tin dịch vụ
        
        
        //Set Thời gian
        txtNgayTra.setText(DateHelper.toString(datPhong.getNgayDi(), "dd/MM/yyyy"));
        String soNgay = null;
        long tg = 0;
        try {
            tg = getSoNgayThue(datPhong.getNgayDen(), datPhong.getNgayDi());
            soNgay = String.valueOf(tg);
        } catch (ParseException e) {
            e.getMessage();
        }
        txtTongTG.setText(soNgay);
        
        //Tính tiền và Set tiền
        tongTien += (phong.getGia() * tg);
        
        txtTongThanhToan.setText(formatTienVND(tongTien));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windown".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhToanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhToanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhToanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhToanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            String soPhong = null;
            new ThanhToanJFrame(soPhong).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox DV001;
    private javax.swing.JCheckBox DV002;
    private javax.swing.JCheckBox DV003;
    private javax.swing.JCheckBox DV004;
    private javax.swing.JCheckBox DV005;
    private javax.swing.JButton btnInHoaDon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtLoaiPhong;
    private javax.swing.JTextField txtNgayTra;
    private javax.swing.JTextField txtSoPhong;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTongTG;
    private javax.swing.JTextField txtTongThanhToan;
    // End of variables declaration//GEN-END:variables

    void init(){
        setLocationRelativeTo(null);
    }
    
    //Tính số ngày
    private long getSoNgayThue(Date ngayDen, Date ngayDi) throws ParseException {
        long diffDays = 0;
        try {
        String ngayDen1 = DateHelper.toString(ngayDen, "dd/MM/yyyy");
        String ngayDi1 = DateHelper.toString(ngayDi, "dd/MM/yyyy");
        
        Date date1 = new SimpleDateFormat("dd/MM/yyyy").parse(ngayDen1);
        Date date2 = new SimpleDateFormat("dd/MM/yyyy").parse(ngayDi1);

        long diff = date2.getTime() - date1.getTime();
        diffDays = diff / (24 * 60 * 60 * 1000);
        } catch (ExceptionInInitializerError e) {
            e.getMessage();
        }
        return diffDays;
    }
    
    //Định dạng tiền
    private static String formatTienVND(double giaTien) {
        DecimalFormat decimalFormat = new DecimalFormat("#,##0 VND");
        return decimalFormat.format(giaTien);
    }
}
